### ISSUE TITLE
Support for Ani-cli

### ISSUE THREAD

**Issue by McUberStein** [m4tx/tundra#6]
It'd be great if Tundra supported ani-cli. Right now the anime I'm watching doesn't even show up on Tundra.

**Comment by m4tx** [comment]
Hey, it seems that ani-cli uses mpv under the hood. Have you tried using https://github.com/hoyon/mpv-mpris? It might just do the trick.

An automatic mpv integration would unfortunately be difficult, as mpv does not offer any kind of API by default. There is an JSON IPC, but it needs to be manually enabled anyway.

**Comment by McUberStein** [comment]
Tried MPRIS. Unfortunately it didn't work. I made sure that the plugin was in fact working, by using playerctl, and I could control mpv with it just fine.

**Comment by McUberStein** [comment]
I think I might just get it to work by downloading individual episodes and watching those. It's worth a try at least.

**Comment by McUberStein** [comment]
Didn't seem to work unfortunately

**Comment by McUberStein** [comment]
Ok, I think I got it. The problem was, that the first letter in the name of the downloaded episode wasn't capitalized. So if there was a way to change what ani-cli names the episodes, it could theoretically work, but I'm very new to Linux and I have absolutely no idea what I'm doing.

**Comment by Hikandy** [comment]
@Goldenbeasty hopefully you can try to do something regarding this, it'll be such a great qol feature

**Comment by m4tx** [comment]
It seems like it should be working with b8b87f40f9b27eede1caa9d67e1467a6e9ad651c now (given that you have mpv-mpris installed as well). Please check the git version if you can, or otherwise this change will be included in the next Tundra release (probably around march-april, as I'm waiting for Gnome 42 SDK to be released).

![Screenshot from 2022-02-19 16-14-06](https://user-images.githubusercontent.com/3128220/154806913-10514b59-7a7c-42e4-86c3-e5e880e9a208.png)

**Comment by McUberStein** [comment]
Can confirm, git version does scrobble ani-cli episodes. Thanks!

**Comment by Hikandy** [comment]
@m4tx tundra-cli (tundra daemon) doesn't seem to work with ani-cli, can you please fix this too?
